// Centralized SEO helpers for the member/public web app.
//
// Everything that needs an absolute URL (canonical tags, sitemap entries, OG
// images) flows through here so there is one source of truth for the public
// origin + brand. Configure via env (see .env.example); sensible localhost
// defaults keep dev working with zero setup.
import type { Metadata } from "next";

export const SITE_NAME = process.env.NEXT_PUBLIC_SITE_NAME?.trim() || "LMS";

// Public origin of THIS web app (no trailing slash). Used for canonical URLs,
// the sitemap, and resolving relative OG images. Falls back to the local dev
// port (next dev -p 3002).
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3002"
).replace(/\/$/, "");

export const SITE_DESCRIPTION =
  process.env.NEXT_PUBLIC_SITE_DESCRIPTION?.trim() ||
  "Courses, memberships, and resources for members.";

// Branded fallback share image (generated by app/opengraph-image.tsx). Routes
// that set their own `openGraph` replace the file-convention default, so
// buildMetadata references this path explicitly to keep an image on every page.
export const DEFAULT_OG_IMAGE = "/opengraph-image";

// Resolve a path (or already-absolute URL) against the public origin.
export function absoluteUrl(pathOrUrl = "/"): string {
  if (/^https?:\/\//i.test(pathOrUrl)) return pathOrUrl;
  try {
    return new URL(pathOrUrl, SITE_URL + "/").toString();
  } catch {
    return SITE_URL;
  }
}

type BuildMetadataArgs = {
  title?: string; // bare title; the root layout adds the " | <brand>" suffix
  description?: string;
  path: string; // canonical path, e.g. "/blog/my-post"
  image?: string | null; // OG/Twitter image (absolute or site-relative)
  imageAlt?: string;
  type?: "website" | "article";
  publishedTime?: string | null; // article only (ISO)
  modifiedTime?: string | null; // article only (ISO)
  authors?: string[]; // article only
  noindex?: boolean;
};

// Build a complete, consistent Metadata object: title + description, a
// self-referencing canonical, a fully-specified OpenGraph object, and a
// matching Twitter card. Next merges this over the root layout defaults.
export function buildMetadata(a: BuildMetadataArgs): Metadata {
  // Always carry an image: the per-page one if given, else the branded default.
  const image = absoluteUrl(a.image || DEFAULT_OG_IMAGE);
  const ogImages = [{ url: image, alt: a.imageAlt || a.title || SITE_NAME }];
  const isArticle = a.type === "article";

  return {
    title: a.title,
    description: a.description,
    alternates: { canonical: a.path },
    openGraph: {
      type: a.type ?? "website",
      siteName: SITE_NAME,
      locale: "en_US",
      url: a.path,
      title: a.title ?? SITE_NAME,
      description: a.description,
      images: ogImages,
      ...(isArticle
        ? {
            publishedTime: a.publishedTime ?? undefined,
            modifiedTime: a.modifiedTime ?? undefined,
            authors: a.authors,
          }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: a.title ?? SITE_NAME,
      description: a.description,
      images: [image],
    },
    ...(a.noindex ? { robots: { index: false, follow: false } } : {}),
  };
}
